import { getAccessToken } from './firebaseAuth.ts';

export interface SendLoginAlertParams {
  toEmail: string;
  userName: string;
  key: string;
  deviceInfo: string;
  timestamp: string;
  communityName?: string;
  availableKeysRemaining?: number;
}

/**
 * Encodes string to RFC 4648 Base64URL safe format
 */
function toBase64Url(str: string): string {
  const utf8Bytes = new TextEncoder().encode(str);
  let binary = '';
  for (let i = 0; i < utf8Bytes.length; i++) {
    binary += String.fromCharCode(utf8Bytes[i]);
  }
  return btoa(binary)
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/, '');
}

/**
 * Sends an email notification to the admin's Gmail inbox using the Gmail API
 */
export async function sendGmailLoginAlert(params: SendLoginAlertParams): Promise<{ success: boolean; messageId?: string; error?: string }> {
  const token = getAccessToken();
  if (!token) {
    return {
      success: false,
      error: 'Gmail is not connected. Please connect your Gmail account to receive login alerts.',
    };
  }

  const subject = `🎓 [StudySync] New Member Joined: ${params.userName} (${params.key})`;

  const htmlBody = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #070b13; color: #f1f5f9; padding: 20px; }
    .card { background: #0d1424; border: 1px solid #1e293b; border-radius: 16px; padding: 24px; max-width: 540px; margin: 0 auto; }
    .header { border-bottom: 1px solid #1e293b; padding-bottom: 16px; margin-bottom: 16px; }
    .badge { background: rgba(6, 182, 212, 0.15); color: #22d3ee; padding: 4px 10px; border-radius: 100px; font-size: 12px; font-weight: bold; }
    .title { color: #ffffff; font-size: 20px; font-weight: 800; margin: 12px 0 4px 0; }
    .row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #1e293b; font-size: 13px; }
    .label { color: #94a3b8; }
    .value { color: #f8fafc; font-weight: 600; font-family: monospace; }
    .footer { font-size: 11px; color: #64748b; margin-top: 20px; text-align: center; }
  </style>
</head>
<body>
  <div class="card">
    <div class="header">
      <span class="badge">StudySync WhatsApp Community Alert</span>
      <h2 class="title">New Member Login Verified 🚀</h2>
      <p style="color: #94a3b8; font-size: 13px; margin: 0;">A student has redeemed an activation key and joined your WhatsApp community.</p>
    </div>

    <div class="row">
      <span class="label">Member Name:</span>
      <span class="value" style="color: #38bdf8;">${params.userName}</span>
    </div>

    <div class="row">
      <span class="label">Activation Key:</span>
      <span class="value" style="color: #34d399;">${params.key}</span>
    </div>

    <div class="row">
      <span class="label">Bound Physical Device:</span>
      <span class="value">${params.deviceInfo}</span>
    </div>

    <div class="row">
      <span class="label">Login Timestamp:</span>
      <span class="value">${new Date(params.timestamp).toLocaleString()}</span>
    </div>

    ${params.availableKeysRemaining !== undefined ? `
    <div class="row">
      <span class="label">Available Keys Remaining:</span>
      <span class="value" style="color: #fbbf24;">${params.availableKeysRemaining} / 1000</span>
    </div>
    ` : ''}

    <div class="footer">
      Automated alert generated by StudySync Single-Device Key Gateway & Google Workspace Gmail API.
    </div>
  </div>
</body>
</html>
  `.trim();

  // Construct standard RFC 2822 email
  const emailLines = [
    `To: ${params.toEmail}`,
    `Subject: =?utf-8?B?${btoa(unescape(encodeURIComponent(subject)))}?=`,
    'MIME-Version: 1.0',
    'Content-Type: text/html; charset=utf-8',
    'Content-Transfer-Encoding: 7bit',
    '',
    htmlBody,
  ];

  const rawEmail = emailLines.join('\r\n');
  const base64UrlMessage = toBase64Url(rawEmail);

  try {
    const res = await fetch('https://gmail.googleapis.com/gmail/v1/users/me/messages/send', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ raw: base64UrlMessage }),
    });

    if (!res.ok) {
      const errText = await res.text();
      console.error('Gmail API send error:', errText);
      return { success: false, error: `Gmail error ${res.status}: ${errText}` };
    }

    const data = await res.json();
    return { success: true, messageId: data.id };
  } catch (err: unknown) {
    console.error('Failed to send email via Gmail:', err);
    return {
      success: false,
      error: err instanceof Error ? err.message : 'Unknown network error',
    };
  }
}
